version: '3.5'

services:
  backend:
    container_name: predi-backend
    build:
      context: ./api
      target: development-build-stage
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    container_name: predi-front
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    restart: unless-stopped
    
